version: 2
jobs:

  checkout_code:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/stakit
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/stakit

  build_app:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/stakit/stakit
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: gradle shadowJar
      - save_cache:
          key: v1-app-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/stakit

  build_ui:
    docker:
      - image: circleci/node:4.8.2
    working_directory: ~/stakit/stakit-ui
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm install
      - run: npm run-script build
      - save_cache:
          key: v1-ui-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/stakit

  build_images:
    machine: true
    working_directory: ~/stakit
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - v1-app-{{ .Environment.CIRCLE_SHA1 }}
            - v1-ui-{{ .Environment.CIRCLE_SHA1 }}
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t noteax/stakit:latest .
      - run: docker push noteax/stakit:latest

workflows:
  version: 2
  build-all:
    jobs:
      - checkout_code
      - build_app:
          requires:
            - checkout_code
      - build_ui:
          requires:
            - checkout_code
      - build_images:
          requires:
            - build_app
            - build_ui
      - deploy:
          requires:
            - build_images
