version: 2
jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/stakit
    steps:
      - checkout
      - run: gradle shadowJar

  build-ui:
    docker:
      - image: circleci/node:4.8.2
    working_directory: ~/stakit-ui
     steps:
      - checkout
      - run: npm run-script build

  build-images:
   machine: true
   steps:
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: docker build -t noteax/stakit:latest .
     - run: docker push noteax/stakit:latest

workflows:
  version: 2
  build-all:
    jobs:
      - build
      - build-ui
      - build-images
      - deploy



